# Generated by Django 4.2.30 on 2026-06-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='student',
        ),
    ]
