# Generated by Django 4.2.30 on 2026-07-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
